/* CREATE DATABASE restaurante; 
USE restaurante; 
*/

CREATE TABLE PEDIDO (
    ID INT PRIMARY KEY,
    DATA DATE,
    ID_RESTA INT,
    VALOR DECIMAL(10, 2),
    TAXA_ENTREGA DECIMAL(10, 2),
    ID_PROMO INT,
    ID_STATUS_ENTREGA INT,
    ID_FORMA_PAG INT,
    OBS TEXT,
    TROCO DECIMAL(10, 2),
    ID_ENDE INT
);

CREATE TABLE PEDIDO_PRODUTO (
    ID_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO)
);

CREATE TABLE PEDIDO_PRODUTO_ACOMP (
    ID_PEDIDO_PRODUTO INT,
    ID_ACOMP INT,
    PRIMARY KEY (ID_PEDIDO_PRODUTO, ID_ACOMP)
);

CREATE TABLE RESTAURANTE (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100),
    ENDERECO VARCHAR(200),
    TELEFONE VARCHAR(20),
    CATEGORIA INT,
    HORA_FUNCIONAMENTO TIME,
    IS_RETIRADA BOOLEAN
);

CREATE TABLE ENDERECO (
    ID INT PRIMARY KEY,
    RUA VARCHAR(100),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(10),
    ID_USUARIO INT
);

CREATE TABLE PROMOCAO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50),
    CODIGO VARCHAR(20),
    VALOR DECIMAL(10, 2),
    VALIDADE DATE
);

CREATE TABLE AVALIACAO (
    ID INT PRIMARY KEY,
    NOTA INT,
    PEDIDO INT,
    REGISTRO_DATA DATE
);

CREATE TABLE PRODUTO_ACOMP (
    ID_PRODUTO INT,
    ID_ACOMP INT,
    PRIMARY KEY (ID_PRODUTO, ID_ACOMP)
);

CREATE TABLE STATUS_ENTREGA (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50)
);

CREATE TABLE ACOMPANHAMENTO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(50),
    DESCRICAO TEXT,
    VALOR DECIMAL(10, 2)
);

CREATE TABLE CATEGORIA (
    ID INT PRIMARY KEY,
    TIPO VARCHAR(50),
    NOME VARCHAR(50),
    DESCRICAO TEXT
);

CREATE TABLE FORMA_PAGAMENTO (
    ID INT PRIMARY KEY,
    TIPO_DE_PAGAMENTO VARCHAR(50)
);

CREATE TABLE HISTORICO_ENTREGA (
    ID INT PRIMARY KEY,
    ID_STATUS_ENTREGA INT,
    ID_PEDIDO INT,
    DATA_HORA DATETIME
);

CREATE TABLE HISTORICO_PAGAMENTO (
    ID INT PRIMARY KEY,
    DATA DATE,
    ID_FORMA INT,
    VALOR DECIMAL(10, 2)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY,
    NOME VARCHAR(100),
    DESCRICAO TEXT,
    PRECO DECIMAL(10, 2),
    CATEGORIA_ID INT,
    RESTAURANTE_ID INT
);

CREATE TABLE RESTAURANTE_PAGAMENTO (
    ID_RES INT,
    ID_PAGA INT,
    PRIMARY KEY (ID_RES, ID_PAGA)
);